apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: maas-discovery-rbac

resources:
- serviceaccount.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- role-ai-tenants.yaml
- role-openshift-ingress.yaml
